//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuctionTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuctionTemplate()
        {
            this.Lots = new HashSet<Lot>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime ModifidedDateTime { get; set; }
        public bool IsStopped { get; set; }
        public long AuthorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lot> Lots { get; set; }
        public virtual User Author { get; set; }
        public System.DateTime? StartedDateTime { get; set; }
    }
}
