//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lot()
        {
            this.Auctions = new HashSet<Auction>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid AuctionTemplateId { get; set; }
        public string Context { get; set; }
        public Nullable<System.DateTime> Duration { get; set; }
        public decimal StartingPrice { get; set; }
        public short Direction { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime ModifidedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auction> Auctions { get; set; }
        public virtual AuctionTemplate AuctionTemplate { get; set; }
    }
}
